name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]   # Trigger on push to main
  pull_request:
    branches: [ "main" ]   # Trigger on PR to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven   # ⚡ Cache Maven dependencies for speed

      - name: Build project with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract project version
        id: vars
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            bhanuprasad22/student-demo-springboot:latest
            bhanuprasad22/student-demo-springboot:${{ env.VERSION }}
